# Generated by Django 2.2.13 on 2021-01-24 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Validator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('cuota', models.IntegerField(blank=True, default=0)),
                ('resto', models.IntegerField(blank=True, default=0)),
                ('texto', models.CharField(db_column='texto', max_length=5000)),
                ('predict', models.CharField(blank=True, max_length=50000)),
                ('is_member', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validadores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
